### PR TITLE
Halo style menu

### PR DESCRIPTION
**Pull request by sabianroberts**

### CODE REVIEW

**Comment by KevDoy** [comment]
Hi @sabianroberts could you please attach some screenshots in here? I’ll be testing later this week/early next. Would love to see it before then though.

**Comment by KevDoy** [comment]
@sabianroberts merged. Thank you so much, looks great. Do you think you could move the text back to the left though? That would be highly appreciated. We also added our Firing Range option for single player practice.

**Comment by sabianroberts** [comment]
> @sabianroberts merged. Thank you so much, looks great. Do you think you could move the text back to the left though? That would be highly appreciated. We also added our Firing Range option for single player practice.

Sure I can do that, there's also I couple other changes I can suggest so I can open another PR soon

**Comment by sabianroberts** [comment]
> @sabianroberts merged. Thank you so much, looks great. Do you think you could move the text back to the left though? That would be highly appreciated. We also added our Firing Range option for single player practice.

I have restored the text back to the left in #12

**Pull request merged**
